# to write

version: "3.3"  # optional since v1.27.0
services:
  alice-front:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    command: bash /root/.yarn/bin/yarn start